### ISSUE TITLE
Clear path to where dfu sources are and how to rebuild

### ISSUE THREAD

**Issue by arfoll** [01org/intel-arduino-tools#45]
Specifically for Linux it would be nice to get build instructions for dfu and everything in x86/bin with matching sources.

**Comment by bbaltz505** [comment]
The current dfu-util used is hosted here:
https://github.com/arduino/dfu-utils-cross 
The repo includes build instructions

The remaining items in x86/bin will be added soon.

**Comment by bbaltz505** [comment]
The DFU-Utils-Cross repo hosted by Arduino has the build instructions documented. Our binaries are maintained in this repo.
The Bash, Cygwin and LSZ binaries all came from the sites listed in the README
The only source code that is built in this rrepo is the GO-based "arduino101load" script. That folder contains the GO source and build instructions.
