### ISSUE TITLE
Drivers not found

### ISSUE THREAD

**Issue by mstfldmr** [01org/intel-arduino-tools#66]
I installed the latest Arduino IDE (1.6.13) and Intel Curie Boards Library (1.0.7) on my Windows 8.1 laptop.

When I plug in Arduino 101 to my laptop, it is detected and Genuino 101 is listed under Other Devices title in Device Manager. Hardware ID is: USB\VID_8087&PID_0AB6&REV_8087 and USB\VID_8087&PID_0AB6

![screenshot 2016-12-07 15 48 23](https://cloud.githubusercontent.com/assets/2570317/20969531/09a26922-bc92-11e6-9824-44ff94625c5f.png)

However, its driver can not be installed. When I try installing the driver, it says: "The system can not find the file specified". 

![screenshot 2016-12-07 15 42 45](https://cloud.githubusercontent.com/assets/2570317/20969532/09be73ce-bc92-11e6-806b-acd85dfdc311.png)

Also, there is no suitable port for Arduino in the IDE.

![screenshot 2016-12-07 15 57 43](https://cloud.githubusercontent.com/assets/2570317/20969533/09c33b2a-bc92-11e6-997a-d22fd70affdf.png)

I tried with different USB cables, Arduino 101s. I also tried reinstalling the IDE and different versions of the library.

After I go to the folder C:\Users\<User Name>\AppData\Local\Arduino15\packages\Intel\tools\arduino101load\1.6.9+1.28 and run post_install.bat as an administrator, there appears an Arduino 101 USB Composite Device (COM5) under the Ports, and 2 GENUINO 101s under Other Devices in Device Manager. Still, COM5 port is not listed in the IDE.

![screenshot 2016-12-07 16 33 20](https://cloud.githubusercontent.com/assets/2570317/20969633/8e9bae4a-bc92-11e6-90c6-1c19c5b6bc25.png)

**Comment by calvinatintel** [comment]
Tracked here: http://forum.arduino.cc/index.php?topic=440507.0
